name: github_demo
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fluttericon: ^2.0.0
  fluentui_system_icons: ^1.1.138
  gql: ^0.13.1-0
  gql_exec: ^0.3.1-0
  gql_link: ^0.4.1-0
  gql_http_link: ^0.4.1-0
  http: ^0.13.1
  oauth2: ^2.0.0
  url_launcher: ^6.0.2
  provider:
  nested:
  window_to_front:
    path: "packages/window_to_front" 
  flutter_secure_storage: ^5.0.0-beta.5
  shared_preferences: ^2.0.7
  layout:
  flutter_markdown: ^0.6.6
  share_plus: ^2.1.4
  intl: ^0.17.0
  gap: ^2.0.0
  modal_bottom_sheet: ^2.0.0
  built_collection: ^5.1.1
  flutter_chips_input: ^1.10.0
  webview_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.6
  gql_build: ^0.2.1-0
  flutter_lints: ^1.0.0
  mocktail:
  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
